language: cpp
sudo: true

cache: ccahe

addons: {apt: {packages: [yasm]}}

matrix:
  fast_finish: true
  include:
    # the actual compilin'
    # - stage: ArchLinux
    #   os: linux
    #   env: JOB=build-archlinux
    #   services:
    #     - docker
    # - stage: Win-Mingw-x64
    #   os: linux
    #   env:
    #     - JOB=build-mingw
    #     - WINARCH=x64
    #   services:
    #     - docker
    # - stage: Win-Mingw-x64-qtstatic
    #   os: linux
    #   env:
    #     - JOB=build-mingw
    #     - WINARCH=x64
    #     - WITH_QT_STATIC=on
    #   services:
    #     - docker
    # - stage: Win-Mingw-x32
    #   os: linux
    #   env:
    #     - JOB=build-mingw
    #     - WINARCH=x32
    #   services:
    #     - docker
    # - stage: Win-Mingw-x32-qtstatic
    #   os: linux
    #   env:
    #     - JOB=build-mingw
    #     - WINARCH=x32
    #     - WITH_QT_STATIC=on
    #   services:
    #     - docker
    # - stage: Ubuntu14-clang
    #   os: linux
    #   env: JOB=build-ubuntu14
    # - stage: Ubuntu14-clang-qtstatic
    #   os: linux
    #   env:
    #     - JOB=build-ubuntu14
    #     - WITH_QT_STATIC=on
    # - stage: Ubuntu16-gcc
    #   os: linux
    #   env: JOB=build-ubuntu16
    #   services:
    #     - docker
    - stage: Ubuntu16-gcc-qt59
      os: linux
      env: JOB=build-ubuntu16-qt59
      services:
        - docker
    # - stage: MacOS-Xcode9.3
    #   os: osx
    #   osx_image: xcode9.3beta
    #   env: JOB=build-osx
    # - stage: MacOS-Xcode8.3
    #   os: osx
    #   osx_image: xcode8.3
    #   env: JOB=build-osx
    # # for ruby lower version and brew problem, not support
    # # - stage: MacOS-Xcode7.3
    # #   os: osx
    # #   osx_image: xcode7.3
    # #   env: JOB=build-osx
    # - stage: Android-Arm7
    #   os: linux
    #   language: android
    #   env:
    #     - JOB=build-android
    #     - USEARCH=arm
    #   android:
    #     components:
    #       - build-tools-26.0.2
    #       - android-26
    #       - sys-img-armeabi-v7a-android-tv-l
    #       - add-on
    #       - extra
    #     licenses:
    #       - 'android-sdk-preview-license-52d11cd2'
    #       - 'android-sdk-license-.+'
    #       - 'google-gdk-license-.+'
    # - stage: Android-X86
    #   os: linux
    #   language: android
    #   env:
    #     - JOB=build-android
    #     - USEARCH=x86
    #   android:
    #     components:
    #       - build-tools-26.0.2
    #       - android-26
    #       - sys-img-armeabi-v7a-android-tv-l
    #       - add-on
    #       - extra
    #     licenses:
    #       - 'android-sdk-preview-license-52d11cd2'
    #       - 'android-sdk-license-.+'
    #       - 'google-gdk-license-.+'

script: "./.travis/$JOB.sh"

before_install:

before_script:




